# https://goframe.org/docs/web/server-config-file-template

###################### 修改配置文件需要重启服务 ######################
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

i18n:
  path: "./i18n" # 指定语言文件存储的目录路径
  language: zh-CN # 指定默认语言
  delimiters: ["${", "}"] # 指定翻译字符串的定界符,默认为["${", "}"]

# https://goframe.org/docs/core/glog-config
logger:
  path: "./glog" # 日志文件路径。默认为空，表示关闭，仅输出到终端
  file: "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
  prefix: "" # 日志内容输出前缀。默认为空
  level: "all" # 日志输出级别
  timeFormat: "2006-01-02 15:04:05" # 自定义日志输出的时间格式，使用Golang标准的时间格式配置
  ctxKeys: [] # 自定义Context上下文变量名称，自动打印Context的变量到日志中。默认为空
  header: true # 是否打印日志的头信息。默认true
  stdout: true # 日志是否同时输出到终端。默认true
  rotateSize: 0 # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
  rotateExpire: 0 # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
  rotateBackupLimit: 0 # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
  rotateBackupExpire: 0 # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
  rotateBackupCompress: 0 # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
  rotateCheckInterval: "1h" # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时
  stdoutColorDisabled: false # 关闭终端的颜色打印。默认开启
  writerColorEnable: true # 日志文件是否带上颜色。默认false，表示不带颜色

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    type: "mysql"
    host: "127.0.0.1"
    port: "3306"
    user: "root"
    pass: "123456"
    name: "gf_template"
    charset: "utf8mb4"
    timezone: "Local"
    maxIdle: "10" # (可选)连接池最大闲置的连接数(默认10)
    maxOpen: "100" # (可选)连接池最大打开的连接数(默认无限制)
    maxLifetime: "30s" # (可选)连接对象可重复使用的时间长度(默认30秒)
    extra: "parseTime=True" #  (可选)不同数据库的额外特性配置，由底层数据库driver定义，具体有哪些配置请查看具体的数据库driver介绍


  # logger:
  #   path: "../../logger/sql/"
  #   level: "all"
  #   ctxKeys: ["RequestId"] # 用于配置需要从 context.Context 接口对象中读取并输出的键名。
  #   stdout: true # 日志是否同时输出到终端。默认true
